import React from 'react';
import { StyleSheet, Text, View, Image, ScrollView, TouchableOpacity } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { theme } from '../../constants/theme';
import { GlassCard } from '../../components/ui/GlassCard';
import { useWardrobeStore } from '../../store/wardrobeStore';
import { ClothingItem } from '../../types';

export default function OutfitDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { items } = useWardrobeStore();

  // For this demonstration, we'll treat the dynamic ID as a "vibe style" selector
  // In your production app, you would fetch the specific outfit array from a database using this ID
  const displayItems = id === 'minimalist' 
    ? items.filter(item => ['1', '3'].includes(item.id)) // Tee and Sneakers
    : items; // Full rotation fallback

  return (
    <View style={styles.container}>
      {/* Custom Header with Back Button */}
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={24} color={theme.colors.text} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Fit Breakdown</Text>
        <View style={{ width: 40 }} /> {/* Layout Spacer to balance back button */}
      </View>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
        
        {/* Dynamic Showcase Hero */}
        <GlassCard style={styles.heroCard}>
          <Text style={styles.vibeTag}>🔥 CURRENT ROTATION</Text>
          <Text style={styles.outfitTitle}>
            {id ? `${id.charAt(0).toUpperCase() + id.slice(1)} Aesthetic` : 'Curated Look'}
          </Text>
          <Text style={styles.outfitMeta}>Generated by AI Stylist • 3 Items</Text>
        </GlassCard>

        <Text style={styles.sectionHeading}>Garment Checklist</Text>

        {/* List of items making up the look */}
        <View style={styles.itemsContainer}>
          {displayItems.map((item: ClothingItem) => (
            <GlassCard key={item.id} style={styles.itemRow}>
              <Image source={{ uri: item.imageUrl }} style={styles.itemImage} />
              <div style={styles.itemDetails}>
                <Text style={styles.categoryLabel}>{item.category.toUpperCase()}</Text>
                <Text style={styles.vibeLabel}>{item.vibe}</Text>
              </div>
              <Ionicons name="checkmark-circle" size={24} color={theme.colors.primary} />
            </GlassCard>
          ))}
        </View>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: theme.colors.background, 
    paddingTop: 60 
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.lg,
    marginBottom: theme.spacing.lg,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text,
    letterSpacing: 0.5,
  },
  scrollContent: {
    paddingHorizontal: theme.spacing.lg,
    paddingBottom: theme.spacing.xl,
  },
  heroCard: {
    paddingVertical: theme.spacing.xl,
    marginBottom: theme.spacing.xl,
    alignItems: 'flex-start',
  },
  vibeTag: {
    fontSize: 11,
    fontWeight: '800',
    color: theme.colors.primary,
    letterSpacing: 1,
    marginBottom: theme.spacing.sm,
  },
  outfitTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: theme.colors.text,
    marginBottom: 6,
  },
  outfitMeta: {
    fontSize: 13,
    color: theme.colors.textMuted,
  },
  sectionHeading: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: theme.spacing.md,
    letterSpacing: 0.3,
  },
  itemsContainer: {
    gap: theme.spacing.md,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
  },
  itemImage: {
    width: 60,
    height: 75,
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.surface,
  },
  itemDetails: {
    flex: 1,
    marginLeft: theme.spacing.md,
  },
  categoryLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.textMuted,
    letterSpacing: 1,
    marginBottom: 2,
  },
  vibeLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.colors.text,
  },
});